### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by scar17off** [system2k/owopforfunposters#6]
![image](https://user-images.githubusercontent.com/81940406/121783313-89201680-cbb6-11eb-815f-a297899a400b.png)

Error: networking.js:20 WebSocket connection to 'ws://wire.ddns.net:7000/' failed: 
WebSocket connection to 'ws://localhost:25565/' failed: 
run.bat:
node server
run0.bat:
node backserver
How to fix?

**Comment by system2k** [comment]
In app.js in the /dist/ folder, change the address to your server's address. It should be at around line 198.
Replace ws://wire.ddns.net:7000 with ws://localhost:7000

**Comment by scar17off** [comment]
thx
